version: 2

# update weekly (to avoid spam)
updates:
  # bump submodules.
  # updates a submodule to the latest commit on the branch given in .gitmodules.
  # if branch not given, then it defaults to the main/master branch.
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "weekly"
    directory: /
    labels:
      - "dependencies"
      - "changelog:omit"
    # allow certain submodules
    allow:
      - dependency-name: "soc-generator/sims/firesim"
      - dependency-name: "applications/firemarshal"
  # submit a PR for bumping GH-A dependencies
  - package-ecosystem: github-actions
    schedule:
      interval: "weekly"
    directory: /
    labels:
      - "dependencies"
      - "changelog:omit"
