name: setup-nix-env
description: Set up the Chipyard Nix development environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Initialize Nix environment
      run: |
        nix develop --command dependencies/scripts/build-setup.sh \
          --verbose \
          --skip-submodules \
          --skip-ctags \
          --skip-precompile \
          --skip-firesim \
          --skip-marshal \
          --skip-clean
      shell: bash -leo pipefail {0}
